### PR TITLE
Remove dependency check

### LINKED ISSUE #338: Review and/or remove dependency_check / requirements.py code
Hi,
currently we have versions for packages in the pipfile-lock file and in dependency_check/requirements.py.
Am I right that if I want to update a version eg. in order to fix a security fix I need to update version numbers in pipfile-lock and in requirements.py? I think at some point it might happen that because of not being cautious enough versions are not the same in the to files and we run into problems.
Would it not be better to automatically generate the requirements.py file by parsing the pipfile.lock and only have one single-source-of-truth?
Or a more general to understand better: Why do we still need the files in dependency_check? I hope I did not already ask this question before. ;-)

### PR DESCRIPTION
**Pull request by security-companion**
Closes #338

### CODE REVIEW

**Comment by security-companion** [comment]
@codders : I've started removing the dependency check we talked about in issue #398 
Now one test is failing (test_version_manager). Do we still need the checks for new dependencies?
Greetings

**Comment by security-companion** [comment]
Hi @codders,
I agree that it' a good idea to keep on with dependency checking for system/platform dependencies.
Although I am not sure if at the moment I can do that as this would involve digging deeper into the existing code and check what we still need and what not any more.
Perhaps we can come up with something more simple like https://stackoverflow.com/a/24517783
What do you think?
Greetings

**Comment by codders** [comment]
Hi @security-companion ,

I had a go at implementing my version of this in #644 . What do you think?

**Comment by security-companion** [comment]
Hi @codders, thank you very much. Your pull request is obvisously better than mine ;-)
I'll close this one.

**Pull request closed without merging**
