### PR TITLE
Change dependency management

### PR DESCRIPTION
**Pull request by cferreirasuazo**
When we run the project locally using console and API (without docker), we encountered multiple errors. 

1. Dependencies errors running the project.
2. When I try to update the `Pipfile` and add a version number to the dependencies (trying to solve the issues), I receive this error: 
```cmd
[Your Pipfile.lock (0e5612) is out of date. Expected: (52d2fb).]
```

So I changed the file `Pipfile` to `requirements.txt` for installing the dependencies. This approach is used with python too. I have modified the `requirements.txt` file to list all the required dependencies for the project.

I have removed the `Pipfile` and `Pipfile.lock` files as they are no longer needed for dependency management. Also updated the "/extras/docker/Dockerfile" to reflect the changes in the dependency management method.

> We recommend using a specific version for each dependency required. There are some packages that are getting the latest version and this is a bad practice.

3. Upon implementing this approach, I have encountered a dependency warning that pertains to both the `swagger_spec_validator` and `bravado_core` libraries. 

Despite my efforts to upgrade these packages to more recent versions, the warning messages persist. I've also attempted to address the issue by installing the referencing package, yet regrettably, the warning persists even after this installation

### CODE REVIEW

**Comment by luismts** [comment]
Hi @codders,

Hope you are well. We are trying to contribute to this project min order to make stable. We want to know yours thought about this PR.

Please, lets us know if this help to project and if not, what we can do to run this project with/without docker. I know you have a docker image for the API service, but we want the main image running all services. 

Also, it would be nice to have a direct contact with you.

**Comment by codders** [comment]
Hi @cferreirasuazo , @luismts,

First of all, thanks so much for the pull request! It's great to have people helping out and contributing to the project.

@luismts I'm happy to set up a call with you to talk about what you're expectations are and what you're trying to do with the project. I think it should be possible to create the docker image that you want, but I would take a slightly different approach to the one in the pull request. Just drop me a direct message with your e-mail address and I'll reach out to you.

@cferreirasuazo Upgrading the version of python in the Dockerfile makes sense - that's a good change. In general, removing the `Pipfile` and replacing it with `requirements.txt` is a bad idea and I don't want to do that. I'll explain in more detail in the comments on the pull request.

**Comment by codders** [comment]
Hi @cferreirasuazo,

If you're working on the fork, it would be great if you make your pull request to the fork and not directly to the main branch. Before we merge the code into the main branch, I would wish for the API to be in a usable state.

If it's helpful / interesting for you, I can also create a feature branch for your development on the main `w4af/w4af` repository, but the same rule would apply - only merging to `main` when there is an incremental improvement in functionality that we're both happy with.

To answer your questions, I would need more information:

1. What are the errors you encounter when trying to install the necessary dependencies?

3. To make the console work, you will need to allocate a terminal in docker. Try with:

```
docker run -it w4af/w4af_api:20230614 ./w4af_console
```

4. I don't know what tutorial you are using for `pipenv`, but I have never run `pipenv lock` or `pipenv sync`. If you want to edit the installed libraries, *do not* edit the Pipfile. Just run `pipenv install mylibrary==0.3.4` to install `mylibrary` at version `0.3.4`. Pipenv should do the rest.

**Comment by cferreirasuazo** [comment]
Hello @codders, I greatly appreciate your invaluable assistance. I'm excited to share that I've successfully managed to run the console and even made some tests.

At present, I'm in the process of exploring the API functionality. However, I've encountered a minor setback while attempting to run the API, as I'm encountering certification errors in the process.

```
Error: SSL peer certificate or SSH remote key was not OK
```

I've been executing the API using the following command:

```bash
docker run -p 5000:5000 w4af/w4af_api:20230614 w4af_api --i-am-a-developer 0.0.0.0:5000
```

Moving forward, my intention is to initiate API tests, and this involves employing the Insomnia tool to facilitate the scanning procedure. Specifically, I'm utilizing the following parameters for the scan:

URL: `https://localhost:5000/scans/`
HTTP Method: POST

The accompanying request body comprises the subsequent JSON structure:

```json
{
    "target_urls": ["http://megadescargas-new.blogspot.com"],
    "scan_profile": "[profile]\n\nname = test\n\n[grep.strange_headers]\n\n[crawl.web_spider]\nonly_forward = False\nfollow_regex = .*\nignore_regex = \n\n"
}
```

We want to push to this fork to push this fork to the main branch: https://github.com/codders/w4af/tree/feat/w4af_api-support, what are the requirenments needed in order to make that happen? 

Here is my email, cferreirasuazo@gmail.com, so we can setup a direct communication with you as you mention to @luismts.

**Comment by cferreirasuazo** [comment]
Hello @codders, I greatly appreciate your invaluable assistance. I'm excited to share that I've successfully managed to run the console and even made some tests.

1) At present, I'm in the process of exploring the API functionality. However, I've encountered a minor setback while attempting to run the API, as I'm encountering certification errors in the process.

```
Error: SSL peer certificate or SSH remote key was not OK
```

I've been executing the API using the following command:

```bash
docker run -p 5000:5000 w4af/w4af_api:20230614 w4af_api --i-am-a-developer 0.0.0.0:5000
```

Moving forward, my intention is to initiate API tests, and this involves employing the Insomnia tool to facilitate the scanning procedure. Specifically, I'm utilizing the following parameters for the scan:

URL: `https://localhost:5000/scans/`
HTTP Method: POST

The accompanying request body comprises the subsequent JSON structure:

```json
{
    "target_urls": ["http://megadescargas-new.blogspot.com"],
    "scan_profile": "[profile]\n\nname = test\n\n[grep.strange_headers]\n\n[crawl.web_spider]\nonly_forward = False\nfollow_regex = .*\nignore_regex = \n\n"
}
```


2) I want the project to have a stable version for the dependenices. That's why I want to set a version number. Is it a good practice? 



We want to push to this fork to push this fork to the main branch: https://github.com/codders/w4af/tree/feat/w4af_api-support, what are the requirenments needed in order to make that happen? 

Here is my email, cferreirasuazo@gmail.com, so we can setup a direct communication with you.

**Comment by codders** [comment]
Hi @cferreirasuazo ,

Happy to hear you're making progress.

1. I would need a bit more context here about the target you're scanning, but it looks like it might be a `cURL` error: https://stackoverflow.com/questions/14192837/ssl-peer-certificate-or-ssh-remote-key-was-not-ok . If you are accessing the API via the command line / using `cURL`, try passing the `-k` switch to disable certificate verification. The API SSL certificate is self-signed - it won't pass validation.

2. The project has a stable version for the dependencies. The dependencies are pinned by the `Pipfile.lock` - the versions you have will be exactly the versions I have, unless you mess around with the `Pipfile` (which I don't recommend).

3. Requirements for merging to main would be that we write some documentation about what works and what doesn't. If you have some success using the API, we need to document how you're doing that. For example, you can see from the open issues for this project that a couple of people have tried to use the API and had similar problems to you. Before we make the API "active" (in the sense of removing the `--i-am-a-developer` flag), we need to make sure all the most obvious questions are answered.

I'll send you a mail with my details.

**Comment by luismts** [comment]
Hi @codders,

Sorry for delay. Thank you for your support, it's really helpful for us.

### The call
Sure we can do something in that schedule. Please write to me in the following link in order to coordinate. [https://rb.gy/4m0lr ](https://rb.gy/4m0lr ).

### Our expectations

#### General

- We want to use this project as a tool internally.
- We want a stable version of the API, so we can integrate it with our tools.

#### Technical

- [ ] We want to run the **API** and the **console** services within the main product/branch/docker image, not a personal branch. So, every change o PR made the product can have those updates.
- [ ] We want to remove the `--i-am-a-developer` flag.
- [ ] We want to manage queue of scans.
- [ ] We want to use profile created in the system through API.
- [ ] We want the ability to run the project with docker and also locally (in order to debug the project better).

### Pending

#### Requiriments.txt file

> @cferreirasuazo Upgrading the version of python in the Dockerfile makes sense - that's a good change. In general, removing the `Pipfile` and replacing it with `requirements.txt` is a bad idea and I don't want to do that. **I'll explain in more detail in the comments on the pull request.**

I think we think in the same way about this topic, but I'm looking for the comments you mentioned and I can't find them. Can you help me with that?

#### Development branch

> If it's helpful / interesting for you, I can also create a feature branch for your development on the main `w4af/w4af` repository, but the same rule would apply - only merging to `main` when there is an incremental improvement in functionality that we're both happy with.

Normally, changes are made to the main branch when those changes are tested. But it would be nice to have a branch too to do so.

### Conclusion

We are happy to collaborate with you in this project. Let see what we can do together. And let us know how we can support you. Feel free to contact me at any time.

Thanks, @codders !

**Comment by codders** [comment]
Rejecting this PR in favour of #662, which should resolve your issue.

**Pull request closed without merging**
